-- create a databse 
CREATE DATABASE sql_project;
-- use database
USE sql_project;

-- Display first 10 rows from retail_sales table

SELECT *
FROM retail_sales
LIMIT 10;

-- Count total records in the dataset

SELECT COUNT(*) AS total_rows
FROM retail_sales;

-- Find rows with NULL values in important columns

SELECT *
FROM retail_sales
WHERE `Transaction ID` IS NULL
   OR `Product Category` IS NULL
   OR `Total Amount` IS NULL;
   
   
-- Find duplicate transaction IDs

SELECT 
    `Transaction ID`,
    COUNT(*) AS duplicate_count
FROM retail_sales
GROUP BY `Transaction ID`
HAVING COUNT(*) > 1;

-- Calculate total revenue generated by each product category

SELECT 
    `Product Category`,
    SUM(`Total Amount`) AS total_revenue
FROM retail_sales
GROUP BY `Product Category`
ORDER BY total_revenue DESC;

-- Find top 10 customers based on total spending

SELECT 
    `Customer ID`,
    SUM(`Total Amount`) AS total_spending
FROM retail_sales
GROUP BY `Customer ID`
ORDER BY total_spending DESC
LIMIT 10;


-- Calculate total revenue generated by each gender

SELECT 
    Gender,
    SUM(`Total Amount`) AS total_revenue
FROM retail_sales
GROUP BY Gender
ORDER BY total_revenue DESC;

-- Categorize customers into age groups and calculate revenue

SELECT 
    CASE
        WHEN Age < 25 THEN 'Young Adults'
        WHEN Age BETWEEN 25 AND 40 THEN 'Adults'
        ELSE 'Senior Adults'
    END AS age_group,

    SUM(`Total Amount`) AS total_revenue

FROM retail_sales

GROUP BY age_group

ORDER BY total_revenue DESC;


-- Find categories generating above-average revenue using CTE

WITH category_sales AS (

    SELECT 
        `Product Category`,
        SUM(`Total Amount`) AS total_revenue
    FROM retail_sales
    GROUP BY `Product Category`

)

SELECT *
FROM category_sales
WHERE total_revenue >
(
    SELECT AVG(total_revenue)
    FROM category_sales
);



-- Analyze revenue generated each month


SELECT

    MONTH(`Date`) AS sales_month,

    SUM(`Total Amount`) AS monthly_revenue

FROM retail_sales

GROUP BY sales_month

ORDER BY sales_month;


-- Identify products/categories with the
-- highest quantity sold.


SELECT

    `Product Category`,

    SUM(Quantity) AS total_quantity_sold

FROM retail_sales

GROUP BY `Product Category`

ORDER BY total_quantity_sold DESC;
-- ============================================
-- BASIC DATA STORYTELLING / BUSINESS INSIGHTS
-- ============================================


-- Insight 1:
-- The Clothing category generated the highest revenue,
-- indicating strong customer demand and better sales
-- performance compared to other categories.


-- Insight 2:
-- A small group of customers contributed significantly
-- higher spending, showing the importance of high-value
-- customers in total revenue generation.


-- Insight 3:
-- Sales contribution between male and female customers
-- was relatively balanced, showing demand across both
-- customer groups.


-- Insight 4:
-- Adult customers generated the highest revenue,
-- suggesting that the primary target audience falls
-- within the working-age population.


-- Insight 5:
-- Some product categories performed above the overall
-- average revenue, highlighting strong-performing
-- business segments.

-- Insight 6:
-- Monthly sales analysis showed variations in revenue
-- across different months, helping identify sales trends
-- and possible seasonal purchasing patterns.



-- Insight 7:
-- Some product categories recorded higher quantities sold,
-- indicating stronger customer demand and better product
-- performance within the retail dataset.